// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh YOUR_PACKAGE_NAME
// **************************************************************************

// ignore_for_file: unused_import
import 'package:ditonton/main.dart';
import 'package:ditonton/routes.dart';
import 'package:ditonton/injection.dart';

void main(){}