// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh YOUR_PACKAGE_NAME
// **************************************************************************

// ignore_for_file: unused_import
import 'package:presentation/cubit/tv_show_detail_watchlist_cubit.dart';
import 'package:presentation/cubit/tv_show_popular_cubit.dart';
import 'package:presentation/cubit/tv_show_detail_cubit.dart';
import 'package:presentation/cubit/movie_detail_watchlist_cubit.dart';
import 'package:presentation/cubit/movie_top_rated_cubit.dart';
import 'package:presentation/cubit/cubit.dart';
import 'package:presentation/cubit/movie_recommendation_cubit.dart';
import 'package:presentation/cubit/tv_show_top_rated_cubit.dart';
import 'package:presentation/cubit/tv_watchlist_cubit.dart';
import 'package:presentation/cubit/tv_show_airing_cubit.dart';
import 'package:presentation/cubit/watchlist_cubit.dart';
import 'package:presentation/cubit/search_cubit.dart';
import 'package:presentation/cubit/tv_show_recommendation_cubit.dart';
import 'package:presentation/cubit/movie_detail_cubit.dart';
import 'package:presentation/cubit/movie_popular_cubit.dart';
import 'package:presentation/cubit/movie_now_playing_cubit.dart';
import 'package:presentation/presentation.dart';
import 'package:presentation/widgets/widgets.dart';
import 'package:presentation/widgets/sub_heading.dart';
import 'package:presentation/widgets/tv_card.dart';
import 'package:presentation/widgets/app_drawer.dart';
import 'package:presentation/widgets/movie_card_list.dart';
import 'package:presentation/pages/about_page.dart';
import 'package:presentation/pages/popular_movies_page.dart';
import 'package:presentation/pages/tv_list_page.dart';
import 'package:presentation/pages/top_rated_movies_page.dart';
import 'package:presentation/pages/movie_detail_page.dart';
import 'package:presentation/pages/airing_tv_page.dart';
import 'package:presentation/pages/pages.dart';
import 'package:presentation/pages/home_movie_page.dart';
import 'package:presentation/pages/search_page.dart';
import 'package:presentation/pages/tv_detail_page.dart';
import 'package:presentation/pages/popular_tv_page.dart';
import 'package:presentation/pages/watchlist_movies_page.dart';
import 'package:presentation/helper/utilities.dart';
import 'package:presentation/helper/state_enum.dart';
import 'package:presentation/helper/constants.dart';
import 'package:presentation/helper/helper.dart';
import 'package:presentation/helper/styles.dart';

void main(){}