// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh YOUR_PACKAGE_NAME
// **************************************************************************

// ignore_for_file: unused_import
import 'package:data/datasources/movie_local_data_source.dart';
import 'package:data/datasources/tv_remote_data_source.dart';
import 'package:data/datasources/db/db.dart';
import 'package:data/datasources/db/database_helper.dart';
import 'package:data/datasources/tv_local_data_source.dart';
import 'package:data/datasources/movie_remote_data_source.dart';
import 'package:data/datasources/datasources.dart';
import 'package:data/utils/typealias.dart';
import 'package:data/utils/utils.dart';
import 'package:data/models/tv_show_table.dart';
import 'package:data/models/tv_show_detail_model.dart';
import 'package:data/models/movie_detail_model.dart';
import 'package:data/models/movie_model.dart';
import 'package:data/models/movie_response.dart';
import 'package:data/models/models.dart';
import 'package:data/models/genre_model.dart';
import 'package:data/models/tv_show_list_response.dart';
import 'package:data/models/movie_table.dart';
import 'package:data/models/tv_show_model.dart';
import 'package:data/data.dart';
import 'package:data/repositories/repositories.dart';
import 'package:data/repositories/tv_show_repository_impl.dart';
import 'package:data/repositories/movie_repository_impl.dart';

void main(){}