// Mocks generated by Mockito 5.1.0 from annotations
// in presentation/test/cubit/tv_show_detail_watchlist_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:domain/tv/entities/tv_show_detail.dart' as _i8;
import 'package:domain/tv/repository/tv_show_repository.dart' as _i2;
import 'package:domain/tv/usecases/get_tv_show_watchlist_status.dart' as _i4;
import 'package:domain/tv/usecases/remove_tv_show_watchlist.dart' as _i9;
import 'package:domain/tv/usecases/save_tv_show_watchlist.dart' as _i6;
import 'package:domain/utils/failure.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTVShowRepository_0 extends _i1.Fake implements _i2.TVShowRepository {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetTVShowWatchlistStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVShowWatchlistStatus extends _i1.Mock
    implements _i4.GetTVShowWatchlistStatus {
  MockGetTVShowWatchlistStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);
  @override
  _i5.Future<bool> call(int? id) =>
      (super.noSuchMethod(Invocation.method(#call, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [SaveTVShowWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTVShowWatchlist extends _i1.Mock
    implements _i6.SaveTVShowWatchlist {
  MockSaveTVShowWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);
  @override
  _i5.Future<_i3.Either<_i7.Failure, String>> call(
          _i8.TVShowDetail? tvShowDetail) =>
      (super.noSuchMethod(Invocation.method(#call, [tvShowDetail]),
              returnValue: Future<_i3.Either<_i7.Failure, String>>.value(
                  _FakeEither_1<_i7.Failure, String>()))
          as _i5.Future<_i3.Either<_i7.Failure, String>>);
}

/// A class which mocks [RemoveTVShowWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveTVShowWatchlist extends _i1.Mock
    implements _i9.RemoveTVShowWatchlist {
  MockRemoveTVShowWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);
  @override
  _i5.Future<_i3.Either<_i7.Failure, String>> call(int? id) =>
      (super.noSuchMethod(Invocation.method(#call, [id]),
              returnValue: Future<_i3.Either<_i7.Failure, String>>.value(
                  _FakeEither_1<_i7.Failure, String>()))
          as _i5.Future<_i3.Either<_i7.Failure, String>>);
}
